/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BanHang;

import ConnectDatabase.DBConnect;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import NhanVien.QL_Nhan_vien;
import SanPham.QL_San_Pham;
import java.util.ArrayList;

/**
 *
 * @author kieut
 */
public class QL_Ban_Hang extends javax.swing.JPanel implements java.beans.Customizer {

    /**
     * Creates new form QL_Ban_Hang
     */
    public QL_Ban_Hang() {
        initComponents();
        loadData_SAN_PHAM();
        loadData_KHACH_HANG();
    }

    private DefaultTableModel dtm_SAN_PHAM = new DefaultTableModel();

    private void loadData_SAN_PHAM() {
        dtm_SAN_PHAM = new DefaultTableModel();
        try {
            String sql = "select * from SAN_PHAM";
            DBConnect conn = new DBConnect();
            ResultSet rs = conn.Query_Db(sql);
            //Create colum for table
            dtm_SAN_PHAM.addColumn("MA_SAN_PHAM");
            dtm_SAN_PHAM.addColumn("TEN_SAN_PHAM");
            dtm_SAN_PHAM.addColumn("LOAI_SAN_PHAM");
            dtm_SAN_PHAM.addColumn("SO_LUONG");
            dtm_SAN_PHAM.addColumn("DON_GIA");
            while (rs.next()) {
                String str_MA_SAN_PHAM = rs.getString(1);
                String str_TEN_SAN_PHAM = rs.getString(2);
                String str_LOAI_SAN_PHAM = rs.getString(3);
                String str_SO_LUONG = rs.getString(4);
                String str_DON_GIA = rs.getString(5);
                Vector row = new Vector();
                row.addElement(str_MA_SAN_PHAM);
                row.addElement(str_TEN_SAN_PHAM);
                row.addElement(str_LOAI_SAN_PHAM);
                row.addElement(str_SO_LUONG);
                row.addElement(str_DON_GIA);
                dtm_SAN_PHAM.addRow(row);
            }
            tbl_SAN_PHAM.setModel(dtm_SAN_PHAM);
            conn.closeConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void LoadDataFromTable2Control() {
        DefaultTableModel model = (DefaultTableModel) tbl_SAN_PHAM.getModel();
        model.getValueAt(tbl_SAN_PHAM.getSelectedRow(), 0).toString();
        model.getValueAt(tbl_SAN_PHAM.getSelectedRow(), 1).toString();
        model.getValueAt(tbl_SAN_PHAM.getSelectedRow(), 2).toString();
        model.getValueAt(tbl_SAN_PHAM.getSelectedRow(), 3).toString();
        model.getValueAt(tbl_SAN_PHAM.getSelectedRow(), 4).toString();
        txttksp.setText(model.getValueAt(tbl_SAN_PHAM.getSelectedRow(), 0).toString());

    }
    private DefaultTableModel dtm_KHACH_HANG = new DefaultTableModel();

    private void loadData_KHACH_HANG() {
        dtm_KHACH_HANG = new DefaultTableModel();
        try {
            String sql = "select * from KHACH_HANG";
            DBConnect conn = new DBConnect();
            ResultSet Viet = conn.Query_Db(sql);
            //Create colum for table
            dtm_KHACH_HANG.addColumn("MA_KHACH_HANG");
            dtm_KHACH_HANG.addColumn("TEN_KHACH_HANG");
            dtm_KHACH_HANG.addColumn("SO_DIEN_THOAI");
            dtm_KHACH_HANG.addColumn("EMAIL");

            while (Viet.next()) {
                String str_MA_KHACH_HANG = Viet.getString(1);
                String str_TEN_KHACH_HANG = Viet.getString(2);
                String str_SO_DIEN_THOAI = Viet.getString(3);
                String str_EMAIL = Viet.getString(4);

                Vector row = new Vector();
                row.addElement(str_MA_KHACH_HANG);
                row.addElement(str_TEN_KHACH_HANG);
                row.addElement(str_SO_DIEN_THOAI);
                row.addElement(str_EMAIL);

                dtm_KHACH_HANG.addRow(row);
            }
            tbl_kh.setModel(dtm_KHACH_HANG);
            conn.closeConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void LoadDataFromTableControlkh() {
        DefaultTableModel model = (DefaultTableModel) tbl_kh.getModel();
        txtmakh.setText(model.getValueAt(tbl_kh.getSelectedRow(), 0).toString());
        txttenkh.setText(model.getValueAt(tbl_kh.getSelectedRow(), 1).toString());
        txtsdt.setText(model.getValueAt(tbl_kh.getSelectedRow(), 2).toString());
        txtemail.setText(model.getValueAt(tbl_kh.getSelectedRow(), 3).toString());
        txttkkh.setText(model.getValueAt(tbl_kh.getSelectedRow(), 0).toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btntkkh = new javax.swing.JButton();
        txttkkh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kh = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btntksp = new javax.swing.JButton();
        txttksp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_SAN_PHAM = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_soluongsp = new javax.swing.JTextField();
        btn_themvaogiohang = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtmakh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttenkh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_giohang = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txttongtien = new javax.swing.JTextField();
        txt_xoagiohang = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Quản Lý Bán Hàng");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 37, 226, 37));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btntkkh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btntkkh.setText("Tìm Kiếm");
        btntkkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntkkhActionPerformed(evt);
            }
        });

        txttkkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttkkhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(txttkkh, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btntkkh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttkkh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntkkh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(15, 33, 841, 63);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Khách Hàng");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(2, 2, 96, 24);

        tbl_kh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_kh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_kh);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(14, 139, 841, 136);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tổng-hợp-hình-nền-full-HD-1920-x-1080-đẹp-nhất-6.jpg"))); // NOI18N
        jPanel2.add(jLabel14);
        jLabel14.setBounds(0, -4, 870, 290);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 870, 290));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sản Phẩm");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(2, 2, 111, 26);

        btntksp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntksp.setText("Tim Kiếm");

        txttksp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttkspActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txttksp, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btntksp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btntksp, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(txttksp))
                .addContainerGap())
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(18, 35, 840, 60);

        tbl_SAN_PHAM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_SAN_PHAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SAN_PHAMMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_SAN_PHAM);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(14, 130, 842, 146);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Số Lượng");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(67, 328, 93, 31);

        txt_soluongsp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_soluongsp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_soluongsp.setText("0");
        jPanel3.add(txt_soluongsp);
        txt_soluongsp.setBounds(193, 321, 60, 40);

        btn_themvaogiohang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_themvaogiohang.setText("Thêm Vào Giỏ Hàng");
        btn_themvaogiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themvaogiohangActionPerformed(evt);
            }
        });
        jPanel3.add(btn_themvaogiohang);
        btn_themvaogiohang.setBounds(539, 318, 228, 43);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tổng-hợp-hình-nền-full-HD-1920-x-1080-đẹp-nhất-6.jpg"))); // NOI18N
        jPanel3.add(jLabel15);
        jLabel15.setBounds(-5, 1, 880, 390);

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 870, 390));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(null);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Mã Khách Hàng");

        jLabel7.setText("Tên Khách Hàng");

        jLabel8.setText("Số Điện Thoại");

        jLabel9.setText("Email");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Thông Tin Khách Hàng");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmakh, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(txttenkh))
                .addGap(52, 52, 52)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmakh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(14, 48, 736, 127);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Thông Tin Hóa Đơn");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(2, 2, 147, 28);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Giỏ Hàng");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl_giohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_giohang);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Tổng tiền");

        txt_xoagiohang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_xoagiohang.setText("Xóa Khỏi Giỏ Hàng");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_xoagiohang, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_xoagiohang, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29))))
        );

        jPanel5.add(jPanel7);
        jPanel7.setBounds(14, 230, 736, 229);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tổng-hợp-hình-nền-full-HD-1920-x-1080-đẹp-nhất-6.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(-2, -4, 760, 540);

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 140, 760, 540));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Thanh Toán");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 720, 220, 50));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Thoát");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 720, 190, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tổng-hợp-hình-nền-full-HD-1920-x-1080-đẹp-nhất-6.jpg"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1740, 890));
    }// </editor-fold>//GEN-END:initComponents

    private void btntkkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntkkhActionPerformed


    }//GEN-LAST:event_btntkkhActionPerformed

    private void txttkkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttkkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttkkhActionPerformed

    private void txttkspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttkspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttkspActionPerformed

    private void tbl_khMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khMouseClicked
        LoadDataFromTableControlkh();

    }//GEN-LAST:event_tbl_khMouseClicked

    

    private void btn_themvaogiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themvaogiohangActionPerformed
          
        
        
    }//GEN-LAST:event_btn_themvaogiohangActionPerformed

    private void tbl_SAN_PHAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SAN_PHAMMouseClicked

        LoadDataFromTable2Control();
    }//GEN-LAST:event_tbl_SAN_PHAMMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_themvaogiohang;
    private javax.swing.JButton btntkkh;
    private javax.swing.JButton btntksp;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_SAN_PHAM;
    private javax.swing.JTable tbl_giohang;
    private javax.swing.JTable tbl_kh;
    private javax.swing.JTextField txt_soluongsp;
    private javax.swing.JButton txt_xoagiohang;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmakh;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttenkh;
    private javax.swing.JTextField txttkkh;
    private javax.swing.JTextField txttksp;
    private javax.swing.JTextField txttongtien;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setObject(Object bean) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
